#Settings for the site
name: Html cells system
title:  Html cells system
description: New system to align site elements with cells.
baseurl: "https://hiJen14.github.io/html-cells"

#site - variablen for properties cells on a page.
totalMainCells: 10
cellsOnRow: 5

#collection
cells:
  cell1:
    width: ""
    height: ""
    lockedHeight: 0

#Build settings
markdown: kramdown
permalink: pretty
