#Settings for the site
name: Html cells system
title:  Html cells system
description: New system to align site elements with cells.
baseurl: "https://hiJen14.github.io/html-cells"

//site var for cells
cellsCounter: 0

#Build settings
markdown: kramdown
permalink: pretty
