#Settings for the site
name: Html cells system
title:  Html cells system
description: New system to align site elements with cells.
baseurl: "https://hiJen14.github.io/html-cells"

#site - variablen for properties cells on a page.
totalMainCells: 10
cellsOnRow: 5

#collection
cells:
  cell01:
    width: ""
    height: ""
    lockedHeight: 0
  cell02:
    width: ""
    height: ""
     lockedHeight: 0
   cell03:
    width: ""
    height: ""
     lockedHeight: 0
   cell04:
    width: ""
    height: ""
     lockedHeight: 0
   cell05:
    width: ""
    height: ""
     lockedHeight: 0
   cell06:
     width: ""
     height: "5px"
     lockedHeight: 1
   cell07:
     width: ""
     height: "5px"
     lockedHeight: 1
   cell08:
     width: ""
     height: "5px"
     lockedHeight: 1
   cell09:
     width: ""
     height: "5px"
     lockedHeight: 1
   cell10:
     width: ""
     height: "5px"
     lockedHeight: 1

#Build settings
markdown: kramdown
permalink: pretty
