#jeklly Object with info about

cells:
    name: cell01
    width: ""
    height: ""
    lockedHeight: 0

    name: cell02
    width: ""
    height: ""
    lockedHeight: 0

    name: cell03
    width: ""
    height: ""
    lockedHeight: 0

    name: cell04
    width: ""
    height: ""
    lockedHeight: 0

    name: cell05
    width: ""
    height: ""
    lockedHeight: 0

    name: cell06
    width: ""
    height: "5px"
    lockedHeight: 1

    name: cell07
    width: ""
    height: "5px"
    lockedHeight: 1

    name: cell08
    width: ""
    height: "5px"
    lockedHeight: 1

    name: cell09
    width: ""
    height: "5px"
    lockedHeight: 1

    name: cell10
    width: ""
    height: "5px"
    lockedHeight: 1
